services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - VITE_BASE_API_URL=${BASE_API_URL:-http://localhost:8080}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=postgresql://${DB_USER:-manager}:${DB_PASSWORD:-123456}@db:${DB_PORT:-5432}/${DB_NAME:-shopper-taxi}
    depends_on: 
      db: 
        condition: service_healthy
        

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-shopper-taxi}
      POSTGRES_USER: ${DB_USER:-manager}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-manager}", "-d", "${DB_NAME:-shopper-taxi}"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  db_data:
